name: Java CD Release and Deploy Maven Package

on:
  push:
    tags:
      - 'v*' # Trigger only when a tag starting with "v" is pushed

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Authenticate to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "<settings>
          <servers>
           <server>
             <id>github</id>
             <username>${{ github.actor }}</username>
             <password>${{ secrets.PERSONAL_ACCESS_TOKEN }}</password>
           </server>
          </servers>
          </settings>" > $HOME/.m2/settings.xml

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Publish to GitHub Packages
        run: mvn -e clean deploy
